language: "go"
env:
  - GO111MODULE=on
go:
  - "1.11"
  - "1.12"
  - "1.13"
  - "1.14"
script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic
  - bash <(curl -s https://codecov.io/bash)
