.PHONY: update-wordlist pre-commit
pre-commit:
	@go build ./...
	@go vet ./...
	@go mod tidy
	@go fmt ./...
	@go fix ./...
	@go test -race -cover .

update-wordlist:
	@mkdir -p internal/wordlist
	@go run ./update-wordlist/main.go
	@gofmt -w internal/wordlist
