package main

import (
	"context"
	"fmt"
	"html/template"
	"io"
	"log"
	"net/http"
	"os"
	"os/signal"
	"strings"
	"time"
)

const url = "https://raw.githubusercontent.com/bitcoin/bips/master/bip-0039/"
const dirName = "internal/wordlist"

// path => export_name
var langs = map[string]string{
	"chinese_simplified":  "ChineseSimplified",
	"chinese_traditional": "ChineseTraditional",
	"english":             "English",
	"french":              "French",
	"italian":             "Italian",
	"japanese":            "Japanese",
	"korean":              "Korean",
	"spanish":             "Spanish",
	"czech":               "Czech",
	"portuguese":          "Portuguese",
}

const text = `// Code generated by "islishude/bip39/update-wordlist"; DO NOT EDIT.

package wordlist

var {{.Variable}} = []string{ 
{{ range .WordList }}{{if .}} "{{.}}", {{end}} 
{{ end}}
}
`

type Template struct {
	Variable string
	WordList []string
}

var filetpl = template.Must(template.New("data").Parse(text))

var client = &http.Client{}

func updateWordlist(basectx context.Context, path, variable string) error {
	ctx, cancel := context.WithTimeout(basectx, time.Second*10)
	defer cancel()

	reqs, err := http.NewRequestWithContext(ctx, http.MethodGet, fmt.Sprintf("%s%s.txt", url, path), nil)
	if err != nil {
		return err
	}

	resp, err := client.Do(reqs)
	if err != nil {
		return err
	}

	src, err := io.ReadAll(resp.Body)
	if err != nil {
		return err
	}

	if err := resp.Body.Close(); err != nil {
		return err
	}

	wfpath := fmt.Sprintf("%s/%s.go", dirName, path)
	wfile, err := os.OpenFile(wfpath, os.O_CREATE|os.O_TRUNC|os.O_RDWR, 0666)
	if err != nil {
		return err
	}

	data := Template{WordList: strings.Split(string(src), "\n"), Variable: variable}
	if err := filetpl.Execute(wfile, data); err != nil {
		return err
	}
	return wfile.Close()
}

func main() {
	basectx, cancel := signal.NotifyContext(context.Background(), os.Interrupt)
	defer cancel()
	for path, name := range langs {
		log.Printf("Get %s's wordlist\n", name)
		if err := updateWordlist(basectx, path, name); err != nil {
			log.Fatalln(err)
		}
		log.Println("done")
	}
	log.Println("Update successful!")
}
