package main

import (
	"context"
	"fmt"
	"html/template"
	"io"
	"log"
	"net/http"
	"os"
	"os/signal"
	"strings"
	"time"
)

const dirName = "internal/wordlist"

const (
	officialLangURL = "https://raw.githubusercontent.com/bitcoin/bips/master/bip-0039/"
	extraLangURL    = "https://raw.githubusercontent.com/ALADAS-org/Cryptocalc/refs/heads/master/assets/mnemonics/txt/"
)

// path => export_name
var langs = map[string]string{
	"chinese_simplified":  "ChineseSimplified",
	"chinese_traditional": "ChineseTraditional",
	"english":             "English",
	"french":              "French",
	"italian":             "Italian",
	"japanese":            "Japanese",
	"korean":              "Korean",
	"spanish":             "Spanish",
	"czech":               "Czech",
	"portuguese":          "Portuguese",
}

var extraLang = map[string]string{
	"deutsch":   "Deutsch",
	"esperanto": "Esperanto",
	"greek":     "Greek",
	"hindi":     "Hindi",
	"latin":     "Latin",
	"russian":   "Russian",
}

const text = `// Code generated by "islishude/bip39/update-wordlist"; DO NOT EDIT.

package wordlist

var {{.Variable}} = []string{ 
{{ range .WordList }}{{if .}} "{{.}}", {{end}} 
{{ end}}
}
`

type Template struct {
	Variable string
	WordList []string
}

var filetpl = template.Must(template.New("data").Parse(text))

var client = &http.Client{}

func updateWordlist(basectx context.Context, baseURL, path, variable string) error {
	ctx, cancel := context.WithTimeout(basectx, time.Second*10)
	defer cancel()

	reqs, err := http.NewRequestWithContext(ctx, http.MethodGet, fmt.Sprintf("%s%s.txt", baseURL, path), nil)
	if err != nil {
		return err
	}

	resp, err := client.Do(reqs)
	if err != nil {
		return err
	}

	src, err := io.ReadAll(resp.Body)
	if err != nil {
		return err
	}

	if err := resp.Body.Close(); err != nil {
		return err
	}

	list := strings.Split(string(src), "\n")
	wordMap := make(map[string]struct{}, len(list))
	for _, w := range list {
		if w == "" {
			continue
		}
		if _, ok := wordMap[w]; ok {
			return fmt.Errorf("duplicate word: %s", w)
		}
		wordMap[w] = struct{}{}
	}
	if len(wordMap) != 2048 {
		return fmt.Errorf("invalid word list length: %d", len(list))
	}

	wfpath := fmt.Sprintf("%s/%s.go", dirName, path)
	wfile, err := os.OpenFile(wfpath, os.O_CREATE|os.O_TRUNC|os.O_RDWR, 0666)
	if err != nil {
		return err
	}

	data := Template{WordList: list, Variable: variable}
	if err := filetpl.Execute(wfile, data); err != nil {
		return err
	}
	return wfile.Close()
}

func main() {
	basectx, cancel := signal.NotifyContext(context.Background(), os.Interrupt)
	defer cancel()
	for path, name := range langs {
		log.Println("Getting word list for", name)
		if err := updateWordlist(basectx, officialLangURL, path, name); err != nil {
			log.Fatalln(err)
		}
		log.Println("done")
	}

	for path, name := range extraLang {
		log.Println("Getting word list for", name)
		if err := updateWordlist(basectx, extraLangURL, path, name); err != nil {
			log.Fatalln(err)
		}
		log.Println("done")
	}

	log.Println("Update successful!")
}
